#!/usr/bin/env node

/**
 * Cake City POS - One-Click Demo Launcher
 * 
 * This script:
 * 1. Creates .env with demo credentials
 * 2. Installs all dependencies
 * 3. Sets up SQLite database (no PostgreSQL needed)
 * 4. Creates owner account
 * 5. Starts backend + frontend
 * 
 * Usage: node start-demo.js
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const crypto = require('crypto');

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[36m',
  red: '\x1b[31m',
};

function log(msg, color = 'reset') {
  console.log(`${colors[color]}${msg}${colors.reset}`);
}

function error(msg) {
  console.error(`${colors.red}✗ ${msg}${colors.reset}`);
}

function success(msg) {
  console.log(`${colors.green}✓ ${msg}${colors.reset}`);
}

function info(msg) {
  console.log(`${colors.blue}ℹ ${msg}${colors.reset}`);
}

async function runCommand(cmd, args, cwd = process.cwd()) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      cwd,
      stdio: 'inherit',
      shell: true,
    });

    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command failed with code ${code}`));
      }
    });

    child.on('error', (err) => {
      reject(err);
    });
  });
}

async function main() {
  console.clear();
  log('╔════════════════════════════════════════╗', 'blue');
  log('║   🍰 CAKE CITY POS - DEMO LAUNCHER     ║', 'blue');
  log('╚════════════════════════════════════════╝', 'blue');
  console.log('');

  const projectRoot = __dirname;

  // Step 1: Create .env file
  log('Step 1/5: Setting up environment...', 'yellow');
  const envPath = path.join(projectRoot, '.env');
  const envContent = `# Cake City POS - Demo Environment
# Auto-generated by start-demo.js

DATABASE_URL=sqlite:./cakecity-demo.db
PORT=4000
JWT_SECRET=${crypto.randomBytes(48).toString('hex')}
CAKE_OWNER_JINA=Demo Cake Shop
CAKE_OWNER_PIN=1234
NODE_ENV=development
CORS_ORIGINS=*
DISABLE_REMINDER_TIMER=false
`;

  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent);
    success('.env created');
  } else {
    info('.env already exists, skipping');
  }

  // Step 2: Install backend dependencies
  log('Step 2/5: Installing backend dependencies...', 'yellow');
  try {
    if (!fs.existsSync(path.join(projectRoot, 'node_modules'))) {
      await runCommand('npm', ['install'], projectRoot);
      success('Backend dependencies installed');
    } else {
      info('Backend dependencies already installed');
    }
  } catch (err) {
    error(`Failed to install backend deps: ${err.message}`);
    process.exit(1);
  }

  // Step 3: Install frontend dependencies
  log('Step 3/5: Installing frontend dependencies...', 'yellow');
  try {
    const webPath = path.join(projectRoot, 'web');
    if (!fs.existsSync(path.join(webPath, 'node_modules'))) {
      await runCommand('npm', ['install'], webPath);
      success('Frontend dependencies installed');
    } else {
      info('Frontend dependencies already installed');
    }
  } catch (err) {
    error(`Failed to install frontend deps: ${err.message}`);
    process.exit(1);
  }

  // Step 4: Initialize database
  log('Step 4/5: Setting up database...', 'yellow');
  try {
    await runCommand('npm', ['run', 'db:init'], projectRoot);
    success('Database initialized with demo data');
  } catch (err) {
    error(`Failed to initialize database: ${err.message}`);
    process.exit(1);
  }

  // Step 5: Start servers
  log('Step 5/5: Starting servers...', 'yellow');
  console.log('');

  log('╔════════════════════════════════════════╗', 'green');
  log('║  ✓ SETUP COMPLETE - LAUNCHING APP     ║', 'green');
  log('╚════════════════════════════════════════╝', 'green');
  console.log('');

  info('Backend starting on http://localhost:4000/graphql');
  info('Frontend starting on http://localhost:5173');
  console.log('');

  log('LOGIN CREDENTIALS:', 'yellow');
  log('  Owner ID: 1', 'blue');
  log('  PIN: 1234', 'blue');
  console.log('');

  log('Press Ctrl+C to stop all servers', 'yellow');
  console.log('');

  // Start backend
  const backendProcess = spawn('npm', ['run', 'dev'], {
    cwd: projectRoot,
    stdio: 'inherit',
    shell: true,
  });

  // Wait a bit for backend to start
  await new Promise((resolve) => setTimeout(resolve, 3000));

  // Start frontend
  const frontendProcess = spawn('npm', ['run', 'dev'], {
    cwd: path.join(projectRoot, 'web'),
    stdio: 'inherit',
    shell: true,
  });

  // Handle termination
  process.on('SIGINT', () => {
    log('\nShutting down...', 'yellow');
    backendProcess.kill();
    frontendProcess.kill();
    process.exit(0);
  });

  // Keep the process alive
  await Promise.all([
    new Promise(() => backendProcess.on('close', () => {})),
    new Promise(() => frontendProcess.on('close', () => {})),
  ]);
}

main().catch((err) => {
  error(err.message);
  process.exit(1);
});
